import type { Metadata } from "next";
import { Inter, Vollkorn } from "next/font/google";
import "./globals.css";

const vollkorn = Vollkorn({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={vollkorn.className}>
        <div className="py-20 bg-cover bg-center bg-[url('../public/banner.jpg')]">
          <h1 className="py-4 title-banner text-center text-5xl">
            SSP Spectrum Calculator Through SynSSP and PFANT
          </h1>
        </div>
        {children}
      </body>
    </html>
  );
}
